
// Global i18n helper for Memoir
// - Persists selection in localStorage ("memoir.lang")
// - Translates elements with data-i18n / data-i18n-attr
// - Provides MEMOIR_I18N.translate(key, vars) for scripts
// - Emits `memoir:lang` CustomEvent({detail:{code}})

(function () {
  const STORE_KEY = 'memoir.lang';
  const DEFAULT_LANG = 'en';

  const strings = {
    en: {
      brandTitle: 'MEMOIR APP',
      brandTagline: 'Preserve your memories forever',
      navHome: 'Home',
      navRecord: 'Record',
      navStories: 'My Stories',
      navSettings: 'Settings',
      navLogin: 'Sign in',
      footerAbout: 'Memoir helps families capture life stories with beautiful voice capture, AI transcription, and polished AI rewrites.',
      footerLegal: 'Legal & Policies',

      brandKicker: 'Memoir App',
      heroTitleA: 'Preserve Your',
      heroTitleB: 'Memories Forever',
      heroBlurb: 'Record once, keep for generations. Start a recording in one tap, add a title and “when it happened”, then share safely with your family.',

      landingStartCardTitle: 'Start Recording',
      landingStartCardText: 'One tap to begin. Add a title and “when it happened” later. Whisper AI transcribes clearly in your language.',
      landingStartBtn: 'Start Recording',
      landingStoriesCardTitle: 'View My Stories',
      landingStoriesCardText: 'Browse your private library, attach photos, AI-rewrite for clarity, and export.',
      landingStoriesBtn: 'My Stories',

      featuresTitle: 'Why Memoir',
      featuresIntro: 'Capture beautifully, polish with AI, and keep everything safe for your family.',
      f1Title: 'Accurate transcription',
      f1Copy: 'Capture every word with Whisper-powered transcription for high accuracy and clarity.',
      f2Title: 'AI rewrite for families',
      f2Copy: 'Turn your spoken words into polished, engaging stories your family will love to read.',
      f3Title: 'Private or shared',
      f3Copy: 'Keep stories private or share read-only with selected family; everything syncs across your devices.',

      pricingTitle: 'Pricing',
      planFreeName: 'Free',
      planFreePrice: '€0',
      planFreeP1: 'Up to 10 stories',
      planFreeP2: 'Max 2 minutes transcription per story',
      planFreeP3: 'Private library on all your devices',
      planLearnMore: 'Learn more',
      planStorytellerName: 'Storyteller — €6.99/month',
      planStorytellerPrice: '€6.99 / mo',
      planStorytellerP1: 'Up to 2.5 hours / month of AI transcription',
      planStorytellerP2: 'AI Rewrite (polish stories), export to PDF/CSV',
      planStorytellerP3: 'Priority processing',
      planFamilyName: 'Family — €8.99/month',
      planFamilyPrice: '€8.99 / mo',
      planFamilyP1: 'Everything in Storyteller',
      planFamilyP2: 'Share your library with up to 4 read-only family members',
      planFamilyP3: 'Invite by email; revoke anytime',
      planExclusiveName: 'Exclusive — €11.99/month',
      planExclusivePrice: '€11.99 / mo',
      planExclusiveP1: 'Up to 5 hours / month of AI transcription + rewrite',
      planExclusiveP2: 'Family sharing (up to 4)',
      planExclusiveP3: 'Best for active storytellers',
      planSubscribe: 'Subscribe',
      planLabel_free: 'Free',
      planLabel_storyteller: 'Storyteller',
      planLabel_premium: 'Premium Storyteller',
      planLabel_exclusive: 'Exclusive Storyteller',

      recordTitle: 'Record',
      recordGreeting: 'Record, {name}',
      recordPlanFreeNote: 'Free plan: recordings over 2 minutes are not allowed. Upgrade in Settings for higher limits.',
      recordPlanGeneric: 'Plan: {plan}',
      recordMicStart: 'Record',
      recordMicStop: 'Stop',
      recordFree: 'Free',
      recordGuided: 'Guided',
      recordPromptsTitle: "Today's suggested prompts",
      recordPromptsRefresh: 'Suggest other prompts',
      recordNotesLabel: 'Notes (optional)',
      recordNotesPlaceholder: 'Add a quick note…',
      recordMyStories: 'My Stories',
      recordTitleLabel: 'Title',
      recordTitlePlaceholder: 'Story title',
      recordWhenLabel: 'When did this happen?',
      recordWhenPlaceholder: 'e.g. “summer 1945”, “early 2018”, “15 Feb 1972”',
      recordPhotoLabel: 'Add photo (optional)',
      recordTranscriptLabel: 'Transcript',
      recordTranscriptPlaceholder: 'Your words will appear here…',
      recordSaveButton: 'Save story',
      recordSaveButtonSaving: 'Saving…',
      recordTimerLimit: 'Reached 2-minute limit on Free plan — stopping.',
      recordRecordingReady: 'Recording ready. Review details, then press “Save story”.',
      recordTranscribing: 'Transcribing with Whisper AI…',
      recordTranscribingHint: 'Please wait while we create your transcript.',
      recordTranscribeNoSpeech: 'No speech detected.',
      recordTranscribeNoSpeechHint: 'Try recording again if this looks incorrect.',
      recordTranscribeError: 'Transcription unavailable.',
      recordTranscribeErrorHint: 'We could not reach Whisper AI. You can still save the audio.',
      recordTranscribeCompleteHint: 'Transcribed automatically with Whisper AI. Edit before saving if needed.',
      recordSaving: 'Saving your story…',
      recordUploadingAudio: 'Uploading audio…',
      recordUploadingPhoto: 'Uploading photo…',
      recordSaveSuccess: 'Story saved! <a href="/stories.html">Go to My Stories</a>',
      recordSaveFailed: 'Save failed: {error}',
      recordSignInRequired: 'Please sign in again.',
      recordUntitled: 'Untitled',
      recordMicrophoneError: 'Microphone error: {error}',

      storiesTitle: 'My Stories',
      storiesGreeting: 'My Stories, {name}',
      storiesCountLabel: 'Stories',
      storiesFamilyLabel: 'Family Members',
      storiesLibraryIntro: 'Your stories will appear in your private library here.',
      storiesInvitePlaceholder: 'family@email.com',
      storiesInviteButton: 'Invite',
      storiesEmpty: 'No stories yet. Record your first one!',
      storiesNeedSignIn: 'Please <a href="/login.html">sign in</a>.',
      storiesRewriteButton: 'Rewrite with AI',
      storiesContinueButton: 'Continue',
      storiesRewriteWorking: 'Rewriting…',
      storiesRewriteDone: 'Done.',
      storiesRewriteFailed: 'Could not rewrite: {error}',
      storiesInviteEnterEmail: 'Enter an email.',
      storiesInviteSignIn: 'Please sign in first.',
      storiesInviteSending: 'Sending…',
      storiesInviteSaved: 'Invite saved. We’ll email instructions when mail is configured.',
      storiesInviteError: 'Could not save invite: {error}',
      storiesLoadError: 'Could not load stories: {error}',
      storiesVisibility_private: 'private',
      storiesVisibility_shared: 'shared',
      storiesVisibility_public: 'public',
      storiesUntitled: 'Untitled',

      settingsTitle: 'Settings',
      settingsAccount: 'Account',
      settingsAccountChecking: 'Checking your session…',
      settingsAccountSignedOut: 'You are <strong class="warn">not signed in</strong>.',
      settingsAccountSignedIn: 'Signed in as <strong class="ok">{name}</strong> ({email})',
      settingsAccountActionsSignIn: 'Sign in',
      settingsAccountActionsStories: 'My Stories',
      settingsAccountActionsRecord: 'Record',
      settingsAccountActionsSignOut: 'Sign out',
      settingsSubscription: 'Subscription',
      settingsSubscriptionIntro: 'Choose or change your plan.',
      settingsSubscriptionSignIn: 'Sign in to see or change your plan.',
      settingsSubscriptionCurrent: 'Current plan: {plan}',
      settingsBilling: 'Billing',
      settingsBillingCopy: 'View invoices and next renewal.',
      settingsBillingManage: 'Manage billing',
      settingsFaq: 'Help & FAQ',
      settingsFaqItem1: 'Is there a free plan? — Yes, with a 2-minute per recording cap.',
      settingsFaqItem2: 'Which languages are supported? — English, French, Dutch, Spanish for UI; stories can be any language.',
      settingsFaqItem3: 'How is transcription done? — We’ll add automatic transcription on save (coming in beta).',
      settingsPlansHeading: 'Plans & pricing',
      settingsPlansBody: 'Pick the plan that matches how often you record.',
      settingsPlanStorytellerLabel: 'Storyteller — €8.99/month',
      settingsPlanStorytellerP1: '3 hours transcription / month',
      settingsPlanStorytellerP2: 'Share with up to 4 family members (read-only)',
      settingsPlanStorytellerP3: 'Private library',
      settingsPlanPremiumLabel: 'Premium Storyteller — €11.99/month',
      settingsPlanPremiumP1: '6 hours transcription / month',
      settingsPlanPremiumP2: 'Share with up to 4 family members (read-only)',
      settingsPlanPremiumP3: 'Priority processing',
      settingsPlanExclusiveLabel: 'Exclusive Storyteller — €15.99/month',
      settingsPlanExclusiveP1: '10 hours transcription / month',
      settingsPlanExclusiveP2: 'Share with up to 4 family members (read-only)',
      settingsPlanExclusiveP3: 'Priority support',
      settingsPlanButton: 'Subscribe'
    },

    fr: {
      brandTitle: 'MEMOIR APP',
      brandTagline: 'Préservez vos souvenirs pour toujours',
      navHome: 'Accueil',
      navRecord: 'Enregistrer',
      navStories: 'Mes histoires',
      navSettings: 'Paramètres',
      navLogin: 'Connexion',
      footerAbout: 'Memoir aide les familles à capturer les histoires de vie avec une belle prise de voix, des transcriptions IA et des réécritures soignées.',
      footerLegal: 'Mentions légales',

      brandKicker: 'Application Memoir',
      heroTitleA: 'Préservez vos',
      heroTitleB: 'souvenirs pour toujours',
      heroBlurb: 'Enregistrez une fois, gardez pour des générations. Lancez un enregistrement, ajoutez un titre et “quand c’est arrivé”, puis partagez en toute sécurité.',

      landingStartCardTitle: 'Commencer un enregistrement',
      landingStartCardText: 'Un seul geste pour démarrer. Ajoutez le titre et “quand c’est arrivé” plus tard. Transcription Whisper claire dans votre langue.',
      landingStartBtn: 'Enregistrer',
      landingStoriesCardTitle: 'Voir mes histoires',
      landingStoriesCardText: 'Parcourez votre bibliothèque privée, joignez des photos, réécrivez avec l’IA et exportez.',
      landingStoriesBtn: 'Mes histoires',

      featuresTitle: 'Pourquoi Memoir',
      featuresIntro: 'Capturez avec soin, polissez avec l’IA et gardez tout en sécurité pour votre famille.',
      f1Title: 'Transcription précise',
      f1Copy: 'Chaque mot, fidèlement, grâce à Whisper.',
      f2Title: 'Réécriture IA pour la famille',
      f2Copy: 'Transformez la parole en un texte chaleureux et lisible, digne d’un livre.',
      f3Title: 'Privé ou partagé',
      f3Copy: 'Gardez privé ou partagez en lecture seule avec des proches; synchronisé sur tous vos appareils.',

      pricingTitle: 'Tarifs',
      planFreeName: 'Gratuit',
      planFreePrice: '0 €',
      planFreeP1: 'Jusqu’à 10 histoires',
      planFreeP2: '2 minutes de transcription par histoire',
      planFreeP3: 'Bibliothèque privée sur tous vos appareils',
      planLearnMore: 'En savoir plus',
      planStorytellerName: 'Conteur — 6,99 €/mois',
      planStorytellerPrice: '6,99 € / mois',
      planStorytellerP1: 'Jusqu’à 2,5 h/mois de transcription IA',
      planStorytellerP2: 'Réécriture IA, export PDF/CSV',
      planStorytellerP3: 'Traitement prioritaire',
      planFamilyName: 'Famille — 8,99 €/mois',
      planFamilyPrice: '8,99 € / mois',
      planFamilyP1: 'Tout Conteur',
      planFamilyP2: 'Partage avec 4 proches (lecture seule)',
      planFamilyP3: 'Invitations par e-mail; révocation à tout moment',
      planExclusiveName: 'Exclusif — 11,99 €/mois',
      planExclusivePrice: '11,99 € / mois',
      planExclusiveP1: 'Jusqu’à 5 h/mois de transcription + réécriture',
      planExclusiveP2: 'Partage familial (jusqu’à 4)',
      planExclusiveP3: 'Idéal pour conteurs actifs',
      planSubscribe: 'S’abonner',
      planLabel_free: 'Gratuit',
      planLabel_storyteller: 'Conteur',
      planLabel_premium: 'Conteur Premium',
      planLabel_exclusive: 'Conteur Exclusif',

      recordTitle: 'Enregistrer',
      recordGreeting: 'Enregistrer, {name}',
      recordPlanFreeNote: 'Offre gratuite : les enregistrements de plus de 2 minutes ne sont pas autorisés. Passez aux Paramètres pour augmenter la limite.',
      recordPlanGeneric: 'Offre : {plan}',
      recordMicStart: 'Enregistrer',
      recordMicStop: 'Arrêter',
      recordFree: 'Libre',
      recordGuided: 'Guidé',
      recordPromptsTitle: 'Invites suggérées du jour',
      recordPromptsRefresh: 'Suggérer d’autres invites',
      recordNotesLabel: 'Notes (facultatif)',
      recordNotesPlaceholder: 'Ajoutez une note rapide…',
      recordMyStories: 'Mes histoires',
      recordTitleLabel: 'Titre',
      recordTitlePlaceholder: 'Titre de l’histoire',
      recordWhenLabel: 'Quand cela est-il arrivé ?',
      recordWhenPlaceholder: 'ex. “été 1945”, “début 2018”, “15 fév. 1972”',
      recordPhotoLabel: 'Ajouter une photo (facultatif)',
      recordTranscriptLabel: 'Transcription',
      recordTranscriptPlaceholder: 'Vos mots apparaîtront ici…',
      recordSaveButton: 'Enregistrer l’histoire',
      recordSaveButtonSaving: 'Enregistrement…',
      recordTimerLimit: 'Limite de 2 minutes atteinte sur l’offre Gratuite — arrêt.',
      recordRecordingReady: 'Enregistrement prêt. Vérifiez les détails puis appuyez sur « Enregistrer l’histoire ».',
      recordTranscribing: 'Transcription avec Whisper IA…',
      recordTranscribingHint: 'Veuillez patienter pendant la création de votre transcription.',
      recordTranscribeNoSpeech: 'Aucune voix détectée.',
      recordTranscribeNoSpeechHint: 'Réessayez si le résultat semble incorrect.',
      recordTranscribeError: 'Transcription indisponible.',
      recordTranscribeErrorHint: 'Impossible de contacter Whisper IA. Vous pouvez tout de même enregistrer l’audio.',
      recordTranscribeCompleteHint: 'Transcription automatique par Whisper IA. Modifiez avant d’enregistrer si besoin.',
      recordSaving: 'Enregistrement de votre histoire…',
      recordUploadingAudio: 'Téléversement de l’audio…',
      recordUploadingPhoto: 'Téléversement de la photo…',
      recordSaveSuccess: 'Histoire sauvegardée ! <a href="/stories.html">Aller à Mes histoires</a>',
      recordSaveFailed: 'Échec de la sauvegarde : {error}',
      recordSignInRequired: 'Veuillez vous reconnecter.',
      recordUntitled: 'Sans titre',
      recordMicrophoneError: 'Erreur micro : {error}',

      storiesTitle: 'Mes histoires',
      storiesGreeting: 'Mes histoires, {name}',
      storiesCountLabel: 'Histoires',
      storiesFamilyLabel: 'Membres de la famille',
      storiesLibraryIntro: 'Vos histoires apparaîtront dans votre bibliothèque privée ici.',
      storiesInvitePlaceholder: 'famille@email.com',
      storiesInviteButton: 'Inviter',
      storiesEmpty: 'Aucune histoire pour le moment. Enregistrez votre première !',
      storiesNeedSignIn: 'Veuillez <a href="/login.html">vous connecter</a>.',
      storiesRewriteButton: 'Réécrire (IA)',
      storiesContinueButton: 'Continuer',
      storiesRewriteWorking: 'Réécriture…',
      storiesRewriteDone: 'Terminé.',
      storiesRewriteFailed: 'Impossible de réécrire : {error}',
      storiesInviteEnterEmail: 'Saisissez un e-mail.',
      storiesInviteSignIn: 'Veuillez d’abord vous connecter.',
      storiesInviteSending: 'Envoi…',
      storiesInviteSaved: 'Invitation enregistrée. Nous enverrons un e-mail lorsque la messagerie sera configurée.',
      storiesInviteError: 'Impossible d’enregistrer l’invitation : {error}',
      storiesLoadError: 'Impossible de charger les histoires : {error}',
      storiesVisibility_private: 'privé',
      storiesVisibility_shared: 'partagé',
      storiesVisibility_public: 'public',
      storiesUntitled: 'Sans titre',

      settingsTitle: 'Paramètres',
      settingsAccount: 'Compte',
      settingsAccountChecking: 'Vérification de votre session…',
      settingsAccountSignedOut: 'Vous n’êtes <strong class="warn">pas connecté</strong>.',
      settingsAccountSignedIn: 'Connecté en tant que <strong class="ok">{name}</strong> ({email})',
      settingsAccountActionsSignIn: 'Connexion',
      settingsAccountActionsStories: 'Mes histoires',
      settingsAccountActionsRecord: 'Enregistrer',
      settingsAccountActionsSignOut: 'Se déconnecter',
      settingsSubscription: 'Abonnement',
      settingsSubscriptionIntro: 'Choisissez ou changez votre offre.',
      settingsSubscriptionSignIn: 'Connectez-vous pour voir ou modifier votre offre.',
      settingsSubscriptionCurrent: 'Offre actuelle : {plan}',
      settingsBilling: 'Facturation',
      settingsBillingCopy: 'Consultez vos factures et le prochain renouvellement.',
      settingsBillingManage: 'Gérer la facturation',
      settingsFaq: 'Aide & FAQ',
      settingsFaqItem1: 'Y a-t-il une offre gratuite ? — Oui, limitée à 2 minutes par enregistrement.',
      settingsFaqItem2: 'Quelles langues sont prises en charge ? — Interface en anglais, français, néerlandais, espagnol; histoires dans la langue de votre choix.',
      settingsFaqItem3: 'Comment se fait la transcription ? — Nous ajouterons la transcription automatique à l’enregistrement (bientôt en bêta).',
      settingsPlansHeading: 'Offres & tarifs',
      settingsPlansBody: 'Choisissez l’offre adaptée à votre fréquence d’enregistrement.',
      settingsPlanStorytellerLabel: 'Conteur — 8,99 €/mois',
      settingsPlanStorytellerP1: '3 heures de transcription / mois',
      settingsPlanStorytellerP2: 'Partage avec jusqu’à 4 proches (lecture seule)',
      settingsPlanStorytellerP3: 'Bibliothèque privée',
      settingsPlanPremiumLabel: 'Conteur Premium — 11,99 €/mois',
      settingsPlanPremiumP1: '6 heures de transcription / mois',
      settingsPlanPremiumP2: 'Partage avec jusqu’à 4 proches (lecture seule)',
      settingsPlanPremiumP3: 'Traitement prioritaire',
      settingsPlanExclusiveLabel: 'Conteur Exclusif — 15,99 €/mois',
      settingsPlanExclusiveP1: '10 heures de transcription / mois',
      settingsPlanExclusiveP2: 'Partage avec jusqu’à 4 proches (lecture seule)',
      settingsPlanExclusiveP3: 'Support prioritaire',
      settingsPlanButton: 'S’abonner'
    },

    nl: {
      brandTitle: 'MEMOIR APP',
      brandTagline: 'Bewaar je herinneringen voor altijd',
      navHome: 'Home',
      navRecord: 'Opnemen',
      navStories: 'Mijn verhalen',
      navSettings: 'Instellingen',
      navLogin: 'Inloggen',
      footerAbout: 'Memoir helpt families levensverhalen vast te leggen met mooie stemopnames, AI-transcripties en verzorgde herschrijvingen.',
      footerLegal: 'Juridisch & beleid',

      brandKicker: 'Memoir App',
      heroTitleA: 'Bewaar je',
      heroTitleB: 'herinneringen voor altijd',
      heroBlurb: 'Neem één keer op, bewaar voor generaties. Start met één tik, voeg een titel en “wanneer het gebeurde” toe en deel veilig met je familie.',

      landingStartCardTitle: 'Start opname',
      landingStartCardText: 'Met één tik beginnen. Titel en “wanneer” later. Whisper-transcriptie in jouw taal.',
      landingStartBtn: 'Opnemen',
      landingStoriesCardTitle: 'Bekijk mijn verhalen',
      landingStoriesCardText: 'Blader door je privébibliotheek, voeg foto’s toe, herschrijf met AI en exporteer.',
      landingStoriesBtn: 'Mijn verhalen',

      featuresTitle: 'Waarom Memoir',
      featuresIntro: 'Leg mooi vast, poets bij met AI en houd alles veilig voor je familie.',
      f1Title: 'Nauwkeurige transcriptie',
      f1Copy: 'Elke zin betrouwbaar met Whisper.',
      f2Title: 'AI-herschrijven voor familie',
      f2Copy: 'Maak van gesproken tekst warm, leesbaar proza — boekwaardig.',
      f3Title: 'Privé of gedeeld',
      f3Copy: 'Houd privé of deel alleen-lezen met familie; synchronisatie op je apparaten.',

      pricingTitle: 'Pakketten',
      planFreeName: 'Gratis',
      planFreePrice: '€0',
      planFreeP1: 'Tot 10 verhalen',
      planFreeP2: 'Max 2 minuten transcriptie per verhaal',
      planFreeP3: 'Privébibliotheek op al je apparaten',
      planLearnMore: 'Meer info',
      planStorytellerName: 'Verteller — €6,99/maand',
      planStorytellerPrice: '€6,99 / maand',
      planStorytellerP1: 'Tot 2,5 uur/maand transcriptie',
      planStorytellerP2: 'AI-herschrijven, export naar PDF/CSV',
      planStorytellerP3: 'Prioriteit',
      planFamilyName: 'Familie — €8,99/maand',
      planFamilyPrice: '€8,99 / maand',
      planFamilyP1: 'Alles van Verteller',
      planFamilyP2: 'Deel met 4 familieleden (alleen lezen)',
      planFamilyP3: 'Uitnodigen per e-mail; intrekken kan altijd',
      planExclusiveName: 'Exclusief — €11,99/maand',
      planExclusivePrice: '€11,99 / maand',
      planExclusiveP1: 'Tot 5 uur/maand transcriptie + herschrijven',
      planExclusiveP2: 'Delen met familie (tot 4)',
      planExclusiveP3: 'Voor actieve vertellers',
      planSubscribe: 'Abonneren',
      planLabel_free: 'Gratis',
      planLabel_storyteller: 'Verteller',
      planLabel_premium: 'Premium Verteller',
      planLabel_exclusive: 'Exclusieve Verteller',

      recordTitle: 'Opnemen',
      recordGreeting: 'Opnemen, {name}',
      recordPlanFreeNote: 'Gratis pakket: opnames langer dan 2 minuten zijn niet toegestaan. Upgrade in Instellingen voor hogere limieten.',
      recordPlanGeneric: 'Pakket: {plan}',
      recordMicStart: 'Opnemen',
      recordMicStop: 'Stop',
      recordFree: 'Vrij',
      recordGuided: 'Geleid',
      recordPromptsTitle: 'Suggesties van vandaag',
      recordPromptsRefresh: 'Andere suggesties',
      recordNotesLabel: 'Notities (optioneel)',
      recordNotesPlaceholder: 'Voeg een korte notitie toe…',
      recordMyStories: 'Mijn verhalen',
      recordTitleLabel: 'Titel',
      recordTitlePlaceholder: 'Titel van het verhaal',
      recordWhenLabel: 'Wanneer gebeurde dit?',
      recordWhenPlaceholder: 'bijv. “zomer 1945”, “begin 2018”, “15 feb 1972”',
      recordPhotoLabel: 'Foto toevoegen (optioneel)',
      recordTranscriptLabel: 'Transcript',
      recordTranscriptPlaceholder: 'Je woorden verschijnen hier…',
      recordSaveButton: 'Verhaal opslaan',
      recordSaveButtonSaving: 'Opslaan…',
      recordTimerLimit: 'Limiet van 2 minuten bereikt op Gratis pakket — stoppen.',
      recordRecordingReady: 'Opname klaar. Controleer en druk op “Verhaal opslaan”.',
      recordTranscribing: 'Transcriberen met Whisper AI…',
      recordTranscribingHint: 'Even geduld, we maken je transcript.',
      recordTranscribeNoSpeech: 'Geen spraak gevonden.',
      recordTranscribeNoSpeechHint: 'Probeer opnieuw als dit niet klopt.',
      recordTranscribeError: 'Transcriptie niet beschikbaar.',
      recordTranscribeErrorHint: 'Whisper AI was niet bereikbaar. Je kunt het audio toch bewaren.',
      recordTranscribeCompleteHint: 'Automatisch getranscribeerd met Whisper AI. Pas aan vóór het opslaan indien nodig.',
      recordSaving: 'Verhaal wordt opgeslagen…',
      recordUploadingAudio: 'Audio uploaden…',
      recordUploadingPhoto: 'Foto uploaden…',
      recordSaveSuccess: 'Verhaal opgeslagen! <a href="/stories.html">Ga naar Mijn verhalen</a>',
      recordSaveFailed: 'Opslaan mislukt: {error}',
      recordSignInRequired: 'Log opnieuw in.',
      recordUntitled: 'Zonder titel',
      recordMicrophoneError: 'Microfoonfout: {error}',

      storiesTitle: 'Mijn verhalen',
      storiesGreeting: 'Mijn verhalen, {name}',
      storiesCountLabel: 'Verhalen',
      storiesFamilyLabel: 'Familieleden',
      storiesLibraryIntro: 'Je verhalen verschijnen hier in je privébibliotheek.',
      storiesInvitePlaceholder: 'familie@email.com',
      storiesInviteButton: 'Uitnodigen',
      storiesEmpty: 'Nog geen verhalen. Neem je eerste verhaal op!',
      storiesNeedSignIn: 'Log <a href="/login.html">in</a> aub.',
      storiesRewriteButton: 'Herschrijf (AI)',
      storiesContinueButton: 'Doorgaan',
      storiesRewriteWorking: 'Herschrijven…',
      storiesRewriteDone: 'Klaar.',
      storiesRewriteFailed: 'Kon niet herschrijven: {error}',
      storiesInviteEnterEmail: 'Vul een e-mail in.',
      storiesInviteSignIn: 'Log eerst in.',
      storiesInviteSending: 'Versturen…',
      storiesInviteSaved: 'Uitnodiging opgeslagen. We mailen instructies zodra mail actief is.',
      storiesInviteError: 'Uitnodiging opslaan mislukt: {error}',
      storiesLoadError: 'Verhalen konden niet worden geladen: {error}',
      storiesVisibility_private: 'privé',
      storiesVisibility_shared: 'gedeeld',
      storiesVisibility_public: 'openbaar',
      storiesUntitled: 'Zonder titel',

      settingsTitle: 'Instellingen',
      settingsAccount: 'Account',
      settingsAccountChecking: 'Je sessie wordt gecontroleerd…',
      settingsAccountSignedOut: 'Je bent <strong class="warn">niet ingelogd</strong>.',
      settingsAccountSignedIn: 'Ingelogd als <strong class="ok">{name}</strong> ({email})',
      settingsAccountActionsSignIn: 'Inloggen',
      settingsAccountActionsStories: 'Mijn verhalen',
      settingsAccountActionsRecord: 'Opnemen',
      settingsAccountActionsSignOut: 'Uitloggen',
      settingsSubscription: 'Abonnement',
      settingsSubscriptionIntro: 'Kies of wijzig je abonnement.',
      settingsSubscriptionSignIn: 'Log in om je abonnement te zien of te wijzigen.',
      settingsSubscriptionCurrent: 'Huidig abonnement: {plan}',
      settingsBilling: 'Facturatie',
      settingsBillingCopy: 'Bekijk facturen en volgende verlenging.',
      settingsBillingManage: 'Facturatie beheren',
      settingsFaq: 'Help & FAQ',
      settingsFaqItem1: 'Is er een gratis pakket? — Ja, met een limiet van 2 minuten per opname.',
      settingsFaqItem2: 'Welke talen worden ondersteund? — Interface in Engels, Frans, Nederlands, Spaans; verhalen in elke taal.',
      settingsFaqItem3: 'Hoe werkt transcriptie? — Automatische transcriptie bij opslaan (binnenkort in bèta).',
      settingsPlansHeading: 'Pakketten & prijzen',
      settingsPlansBody: 'Kies het pakket dat bij je opnamefrequentie past.',
      settingsPlanStorytellerLabel: 'Verteller — €8,99/maand',
      settingsPlanStorytellerP1: '3 uur transcriptie / maand',
      settingsPlanStorytellerP2: 'Delen met tot 4 familieleden (alleen lezen)',
      settingsPlanStorytellerP3: 'Privébibliotheek',
      settingsPlanPremiumLabel: 'Premium Verteller — €11,99/maand',
      settingsPlanPremiumP1: '6 uur transcriptie / maand',
      settingsPlanPremiumP2: 'Delen met tot 4 familieleden (alleen lezen)',
      settingsPlanPremiumP3: 'Prioriteit',
      settingsPlanExclusiveLabel: 'Exclusieve Verteller — €15,99/maand',
      settingsPlanExclusiveP1: '10 uur transcriptie / maand',
      settingsPlanExclusiveP2: 'Delen met tot 4 familieleden (alleen lezen)',
      settingsPlanExclusiveP3: 'Priority support',
      settingsPlanButton: 'Abonneren'
    },

    es: {
      brandTitle: 'MEMOIR APP',
      brandTagline: 'Conserva tus recuerdos para siempre',
      navHome: 'Inicio',
      navRecord: 'Grabar',
      navStories: 'Mis historias',
      navSettings: 'Ajustes',
      navLogin: 'Acceso',
      footerAbout: 'Memoir ayuda a las familias a capturar historias de vida con una hermosa voz, transcripciones IA y reescrituras cuidadas.',
      footerLegal: 'Avisos legales',

      brandKicker: 'Aplicación Memoir',
      heroTitleA: 'Conserva tus',
      heroTitleB: 'recuerdos para siempre',
      heroBlurb: 'Graba una vez y guarda para generaciones. Comienza con un toque, añade un título y “cuándo ocurrió”, y comparte de forma segura.',

      landingStartCardTitle: 'Comenzar a grabar',
      landingStartCardText: 'Un toque para empezar. Título y fecha después. Transcripción Whisper clara en tu idioma.',
      landingStartBtn: 'Grabar',
      landingStoriesCardTitle: 'Ver mis historias',
      landingStoriesCardText: 'Biblioteca privada, fotos, reescritura con IA y exportación.',
      landingStoriesBtn: 'Mis historias',

      featuresTitle: 'Por qué Memoir',
      featuresIntro: 'Captura con cariño, mejora con IA y guarda todo seguro para tu familia.',
      f1Title: 'Transcripción precisa',
      f1Copy: 'Cada palabra con Whisper, con alta precisión.',
      f2Title: 'Reescritura IA para familias',
      f2Copy: 'Convierte tu voz en relatos pulidos y amenos — literatura familiar.',
      f3Title: 'Privado o compartido',
      f3Copy: 'Mantén privado o comparte de solo lectura con familia; todo se sincroniza en tus dispositivos.',

      pricingTitle: 'Planes',
      planFreeName: 'Gratis',
      planFreePrice: '€0',
      planFreeP1: 'Hasta 10 historias',
      planFreeP2: 'Máx 2 minutos por historia',
      planFreeP3: 'Biblioteca privada en todos tus dispositivos',
      planLearnMore: 'Más información',
      planStorytellerName: 'Narrador — 6,99 €/mes',
      planStorytellerPrice: '6,99 € / mes',
      planStorytellerP1: 'Hasta 2,5 h/mes de transcripción IA',
      planStorytellerP2: 'Reescritura IA, exportación PDF/CSV',
      planStorytellerP3: 'Procesamiento prioritario',
      planFamilyName: 'Familiar — 8,99 €/mes',
      planFamilyPrice: '8,99 € / mes',
      planFamilyP1: 'Todo Narrador',
      planFamilyP2: 'Comparte con hasta 4 familiares (solo lectura)',
      planFamilyP3: 'Invita por correo; revoca cuando quieras',
      planExclusiveName: 'Exclusivo — 11,99 €/mes',
      planExclusivePrice: '11,99 € / mes',
      planExclusiveP1: 'Hasta 5 h/mes de transcripción + reescritura',
      planExclusiveP2: 'Uso familiar (hasta 4)',
      planExclusiveP3: 'Ideal para narradores activos',
      planSubscribe: 'Suscribirse',
      planLabel_free: 'Gratis',
      planLabel_storyteller: 'Narrador',
      planLabel_premium: 'Narrador Premium',
      planLabel_exclusive: 'Narrador Exclusivo',

      recordTitle: 'Grabar',
      recordGreeting: 'Grabar, {name}',
      recordPlanFreeNote: 'Plan gratuito: no se permiten grabaciones de más de 2 minutos. Mejora en Ajustes para límites mayores.',
      recordPlanGeneric: 'Plan: {plan}',
      recordMicStart: 'Grabar',
      recordMicStop: 'Detener',
      recordFree: 'Libre',
      recordGuided: 'Guiado',
      recordPromptsTitle: 'Sugerencias de hoy',
      recordPromptsRefresh: 'Sugerir otras',
      recordNotesLabel: 'Notas (opcional)',
      recordNotesPlaceholder: 'Añade una nota rápida…',
      recordMyStories: 'Mis historias',
      recordTitleLabel: 'Título',
      recordTitlePlaceholder: 'Título de la historia',
      recordWhenLabel: '¿Cuándo ocurrió?',
      recordWhenPlaceholder: 'p.ej. “verano de 1945”, “principios de 2018”, “15 feb 1972”',
      recordPhotoLabel: 'Añadir foto (opcional)',
      recordTranscriptLabel: 'Transcripción',
      recordTranscriptPlaceholder: 'Tus palabras aparecerán aquí…',
      recordSaveButton: 'Guardar historia',
      recordSaveButtonSaving: 'Guardando…',
      recordTimerLimit: 'Límite de 2 minutos alcanzado en el plan Gratis — deteniendo.',
      recordRecordingReady: 'Grabación lista. Revisa y pulsa “Guardar historia”.',
      recordTranscribing: 'Transcribiendo con Whisper IA…',
      recordTranscribingHint: 'Espera mientras creamos tu transcripción.',
      recordTranscribeNoSpeech: 'No se detectó voz.',
      recordTranscribeNoSpeechHint: 'Vuelve a grabar si el resultado no es correcto.',
      recordTranscribeError: 'Transcripción no disponible.',
      recordTranscribeErrorHint: 'No pudimos contactar con Whisper IA. Aun así puedes guardar el audio.',
      recordTranscribeCompleteHint: 'Transcrito automáticamente con Whisper IA. Edita antes de guardar si lo necesitas.',
      recordSaving: 'Guardando tu historia…',
      recordUploadingAudio: 'Subiendo audio…',
      recordUploadingPhoto: 'Subiendo foto…',
      recordSaveSuccess: '¡Historia guardada! <a href="/stories.html">Ir a Mis historias</a>',
      recordSaveFailed: 'Error al guardar: {error}',
      recordSignInRequired: 'Vuelve a iniciar sesión.',
      recordUntitled: 'Sin título',
      recordMicrophoneError: 'Error de micrófono: {error}',

      storiesTitle: 'Mis historias',
      storiesGreeting: 'Mis historias, {name}',
      storiesCountLabel: 'Historias',
      storiesFamilyLabel: 'Miembros de la familia',
      storiesLibraryIntro: 'Tus historias aparecerán en tu biblioteca privada aquí.',
      storiesInvitePlaceholder: 'familia@email.com',
      storiesInviteButton: 'Invitar',
      storiesEmpty: 'Aún no hay historias. ¡Graba la primera!',
      storiesNeedSignIn: 'Por favor <a href="/login.html">inicia sesión</a>.',
      storiesRewriteButton: 'Reescribir (IA)',
      storiesContinueButton: 'Continuar',
      storiesRewriteWorking: 'Reescribiendo…',
      storiesRewriteDone: 'Listo.',
      storiesRewriteFailed: 'No se pudo reescribir: {error}',
      storiesInviteEnterEmail: 'Introduce un correo.',
      storiesInviteSignIn: 'Inicia sesión primero.',
      storiesInviteSending: 'Enviando…',
      storiesInviteSaved: 'Invitación guardada. Enviaremos instrucciones cuando el correo esté configurado.',
      storiesInviteError: 'No se pudo guardar la invitación: {error}',
      storiesLoadError: 'No se pudieron cargar las historias: {error}',
      storiesVisibility_private: 'privado',
      storiesVisibility_shared: 'compartido',
      storiesVisibility_public: 'público',
      storiesUntitled: 'Sin título',

      settingsTitle: 'Ajustes',
      settingsAccount: 'Cuenta',
      settingsAccountChecking: 'Comprobando tu sesión…',
      settingsAccountSignedOut: 'No has <strong class="warn">iniciado sesión</strong>.',
      settingsAccountSignedIn: 'Conectado como <strong class="ok">{name}</strong> ({email})',
      settingsAccountActionsSignIn: 'Acceder',
      settingsAccountActionsStories: 'Mis historias',
      settingsAccountActionsRecord: 'Grabar',
      settingsAccountActionsSignOut: 'Cerrar sesión',
      settingsSubscription: 'Suscripción',
      settingsSubscriptionIntro: 'Elige o cambia tu plan.',
      settingsSubscriptionSignIn: 'Inicia sesión para ver o cambiar tu plan.',
      settingsSubscriptionCurrent: 'Plan actual: {plan}',
      settingsBilling: 'Facturación',
      settingsBillingCopy: 'Consulta facturas y próxima renovación.',
      settingsBillingManage: 'Gestionar facturación',
      settingsFaq: 'Ayuda y preguntas',
      settingsFaqItem1: '¿Hay un plan gratuito? — Sí, con un límite de 2 minutos por grabación.',
      settingsFaqItem2: '¿Qué idiomas hay? — Interfaz en inglés, francés, neerlandés, español; historias en cualquier idioma.',
      settingsFaqItem3: '¿Cómo funciona la transcripción? — Añadiremos transcripción automática al guardar (pronto en beta).',
      settingsPlansHeading: 'Planes y precios',
      settingsPlansBody: 'Elige el plan que encaje con la frecuencia con la que grabas.',
      settingsPlanStorytellerLabel: 'Narrador — 8,99 €/mes',
      settingsPlanStorytellerP1: '3 horas de transcripción / mes',
      settingsPlanStorytellerP2: 'Comparte con hasta 4 familiares (solo lectura)',
      settingsPlanStorytellerP3: 'Biblioteca privada',
      settingsPlanPremiumLabel: 'Narrador Premium — 11,99 €/mes',
      settingsPlanPremiumP1: '6 horas de transcripción / mes',
      settingsPlanPremiumP2: 'Comparte con hasta 4 familiares (solo lectura)',
      settingsPlanPremiumP3: 'Procesamiento prioritario',
      settingsPlanExclusiveLabel: 'Narrador Exclusivo — 15,99 €/mes',
      settingsPlanExclusiveP1: '10 horas de transcripción / mes',
      settingsPlanExclusiveP2: 'Comparte con hasta 4 familiares (solo lectura)',
      settingsPlanExclusiveP3: 'Soporte prioritario',
      settingsPlanButton: 'Suscribirse'
    }
  };

  function pickPack(code) {
    return strings[code] || strings[DEFAULT_LANG];
  }

  function getLang() {
    return localStorage.getItem(STORE_KEY) || DEFAULT_LANG;
  }

  function t(key, code) {
    const lang = code || getLang();
    const pack = pickPack(lang);
    if (Object.prototype.hasOwnProperty.call(pack, key)) return pack[key];
    const fallback = pickPack(DEFAULT_LANG);
    return Object.prototype.hasOwnProperty.call(fallback, key) ? fallback[key] : null;
  }

  function format(template, vars) {
    if (!template || !vars) return template;
    return template.replace(/\{(\w+)\}/g, (_, name) => (vars[name] != null ? vars[name] : `{${name}}`));
  }

  function translate(key, vars, code) {
    const template = t(key, code);
    if (template == null) return null;
    return format(template, vars);
  }

  function each(scope, selector, cb) {
    if (!scope || scope === document) {
      document.querySelectorAll(selector).forEach(cb);
      return;
    }
    if (scope.matches && scope.matches(selector)) cb(scope);
    scope.querySelectorAll(selector).forEach(cb);
  }

  function applyTranslations(code, root) {
    const lang = code || getLang();
    const scope = root || document;

    each(scope, '[data-i18n]', el => {
      const key = el.getAttribute('data-i18n');
      const val = translate(key, null, lang);
      if (val != null) el.textContent = val;
    });

    each(scope, '[data-i18n-html]', el => {
      const key = el.getAttribute('data-i18n-html');
      const val = translate(key, null, lang);
      if (val != null) el.innerHTML = val;
    });

    each(scope, '[data-i18n-attr]', el => {
      const spec = el.getAttribute('data-i18n-attr') || '';
      spec.split(/[;,]/).map(part => part.trim()).filter(Boolean).forEach(entry => {
        const [attr, key] = entry.split(':').map(s => (s || '').trim());
        if (!attr || !key) return;
        const val = translate(key, null, lang);
        if (val != null) el.setAttribute(attr, val);
      });
    });
  }

  function setLang(code) {
    const safe = strings[code] ? code : DEFAULT_LANG;
    localStorage.setItem(STORE_KEY, safe);
    applyTranslations(safe, document);
    window.dispatchEvent(new CustomEvent('memoir:lang', { detail: { code: safe } }));
  }

  function applyAll(root) {
    applyTranslations(getLang(), root || document);
  }

  document.addEventListener('DOMContentLoaded', () => applyAll(document));
  window.addEventListener('memoir:lang', (ev) => {
    const code = ev?.detail?.code;
    if (code) applyTranslations(code, document);
  });

  window.MEMOIR_I18N = {
    strings,
    getLang,
    setLang,
    t: (key, code) => t(key, code),
    translate: (key, vars, code) => translate(key, vars, code),
    format,
    apply: (code, root) => applyTranslations(code, root),
    applyAll
  };
})();
