window.MEMOIR_I18N = (function(){
  const strings = {
    en: {
      // ==== Global
      footerAbout: "Memoir helps families capture life stories with beautiful voice capture, AI transcription, and polished AI rewrites.",
      footerLegal: "Legal & Policies",

      // ==== Hero
      brandKicker: "MEMOIR APP",
      heroTitleA: "Preserve Your",
      heroTitleB: "Memories Forever",
      heroBlurb: "Record once, keep for generations. Start a recording in one tap, add a title and “when it happened”, then share safely with your family.",

      // ==== Mini cards
      miniStartLabel: "Start Recording",
      miniStartCopy: "One tap to begin. Add a title and “when it happened” later.",
      startRecording: "Start Recording",
      miniStoriesLabel: "View My Stories",
      miniStoriesCopy: "Browse, rewrite with AI, export, and share with your family.",
      viewStories: "My Stories",

      // ==== Why Memoir
      whyTitle: "Why Memoir",
      feat1Title: "Accurate transcription",
      feat1Copy: "Capture every word with Whisper-powered transcription for high accuracy and clarity.",
      feat2Title: "AI rewrite for families",
      feat2Copy: "Turn your spoken words into polished, engaging stories — like real literature your family will love to read.",
      feat3Title: "Private or shared",
      feat3Copy: "Keep stories private or share read-only with selected family members; everything syncs across your devices.",

      // ==== Pricing
      pricingTitle: "Pricing",
      tierFreeName: "Free",     tierFreePrice: "€0",
      tierFreeB1: "Up to 10 stories",
      tierFreeB2: "Max 2 minutes transcription each",
      tierFreeB3: "Private library on all your devices",

      tierPremiumName: "Storyteller — €6.99/month",  tierPremiumPrice: "€6.99 / mo",
      tierPremiumB1: "Up to 2.5 hours / month of AI transcription",
      tierPremiumB2: "AI Rewrite (polish stories), export to PDF/CSV",
      tierPremiumB3: "Priority processing",

      tierFamilyName: "Family — €8.99/month",        tierFamilyPrice: "€8.99 / mo",
      tierFamilyB1: "Everything in Storyteller",
      tierFamilyB2: "Share your library with up to 4 read-only family members",
      tierFamilyB3: "Invite by email; revoke anytime",

      tierExclusiveName: "Exclusive — €11.99/month", tierExclusivePrice: "€11.99 / mo",
      tierExclusiveB1: "Up to 5 hours / month of AI transcription + rewrite",
      tierExclusiveB2: "Family sharing (up to 4)",
      tierExclusiveB3: "Best for active storytellers",

      // ==== Record
      recordTitle: "Record",
      recordButton: "Record",
      stop: "Stop",
      recordingHint: "Recording… transcription will appear live when online.",
      listening: "Listening…",
      offlineHint: "Offline — audio saved and will sync later.",
      recordFree: "Free",
      recordGuided: "Guided",
      guidedLead: "Pick a topic to spark your memory:",
      notesLabel: "Notes (optional)",
      notesPlaceholder: "Add a quick note…",
      titleLabel: "Title",
      titlePlaceholder: "Story title",
      whenLabel: "When did this happen?",
      whenPlaceholder: "e.g. “summer 1945”, “early 2018”, “15 Feb 1972”",
      photoLabel: "Add photo (optional)",
      transcriptLabel: "Transcript",
      transcriptEmpty: "Your words will appear here…",
      saveStory: "Save story",
      rewriteHint: "Tip: after saving, use AI Rewrite in “My Stories” to turn this into a polished, book-ready story.",
      storyDefault: "Story",
      noTranscript: "There is no transcript yet. Say a few words, then try again.",
      saved: "Saved! You can find it in My Stories.",
      saveFailed: "Save failed. If you are offline, it will retry when connected.",

      // ==== Stories
      storiesTitle: "My Stories",
      storiesEmpty: "No stories yet. Record your first one!",
      storiesListEmpty: "List is empty.",
      storiesRewrite: "Rewrite with AI",
      storiesExport: "Export",
      storiesDelete: "Delete"
    },

    fr: {
      footerAbout: "Memoir aide les familles à capturer leurs histoires de vie avec une belle capture vocale, une transcription IA et des réécritures soignées.",
      footerLegal: "Mentions légales & Politiques",

      brandKicker: "APPLICATION MEMOIR",
      heroTitleA: "Préservez vos",
      heroTitleB: "Souvenirs pour toujours",
      heroBlurb: "Enregistrez une fois, gardez pour des générations. Lancez un enregistrement en un clic, ajoutez un titre et “quand c’est arrivé”, puis partagez-le en toute sécurité avec votre famille.",

      miniStartLabel: "Commencer l’enregistrement",
      miniStartCopy: "Un clic pour démarrer. Ajoutez un titre et “quand c’est arrivé” plus tard.",
      startRecording: "Commencer",
      miniStoriesLabel: "Voir mes histoires",
      miniStoriesCopy: "Parcourez, réécrivez avec l’IA, exportez et partagez avec votre famille.",
      viewStories: "Mes histoires",

      whyTitle: "Pourquoi Memoir",
      feat1Title: "Transcription précise",
      feat1Copy: "Capturez chaque mot avec la transcription Whisper pour une grande exactitude.",
      feat2Title: "Réécriture IA pour la famille",
      feat2Copy: "Transformez vos paroles en histoires soignées et captivantes, comme de vrais livres à lire en famille.",
      feat3Title: "Privé ou partagé",
      feat3Copy: "Gardez vos histoires privées ou partagez-les en lecture seule avec des proches, synchronisées sur tous vos appareils.",

      pricingTitle: "Tarifs",
      tierFreeName: "Gratuit", tierFreePrice: "0 €",
      tierFreeB1: "Jusqu’à 10 histoires",
      tierFreeB2: "Max 2 minutes de transcription chacune",
      tierFreeB3: "Bibliothèque privée sur tous vos appareils",

      tierPremiumName: "Conteur — 6,99 €/mois", tierPremiumPrice: "6,99 € / mois",
      tierPremiumB1: "Jusqu’à 2,5 heures / mois de transcription IA",
      tierPremiumB2: "Réécriture IA, export PDF/CSV",
      tierPremiumB3: "Traitement prioritaire",

      tierFamilyName: "Famille — 8,99 €/mois", tierFamilyPrice: "8,99 € / mois",
      tierFamilyB1: "Tout dans Conteur",
      tierFamilyB2: "Partagez avec jusqu’à 4 membres en lecture seule",
      tierFamilyB3: "Invitez par email ; révocable à tout moment",

      tierExclusiveName: "Exclusif — 11,99 €/mois", tierExclusivePrice: "11,99 € / mois",
      tierExclusiveB1: "Jusqu’à 5 heures / mois transcription + réécriture IA",
      tierExclusiveB2: "Partage familial (jusqu’à 4)",
      tierExclusiveB3: "Idéal pour les conteurs actifs",

      recordTitle: "Enregistrer",
      recordButton: "Enregistrer",
      stop: "Arrêter",
      recordingHint: "Enregistrement… la transcription apparaîtra en direct.",
      listening: "Écoute…",
      offlineHint: "Hors ligne — audio sauvegardé et synchronisé plus tard.",
      recordFree: "Gratuit",
      recordGuided: "Guidé",
      guidedLead: "Choisissez un sujet pour réveiller vos souvenirs :",
      notesLabel: "Notes (optionnel)",
      notesPlaceholder: "Ajouter une note rapide…",
      titleLabel: "Titre",
      titlePlaceholder: "Titre de l’histoire",
      whenLabel: "Quand cela s’est-il passé ?",
      whenPlaceholder: "ex. “été 1945”, “début 2018”, “15 fév. 1972”",
      photoLabel: "Ajouter une photo (optionnel)",
      transcriptLabel: "Transcription",
      transcriptEmpty: "Vos mots apparaîtront ici…",
      saveStory: "Enregistrer l’histoire",
      rewriteHint: "Astuce : utilisez Réécriture IA dans “Mes histoires” pour transformer vos récits en belles histoires.",
      storyDefault: "Histoire",
      noTranscript: "Pas encore de transcription. Dites quelques mots puis réessayez.",
      saved: "Enregistré ! Retrouvez-le dans Mes histoires.",
      saveFailed: "Échec de l’enregistrement. Réessai automatique si vous êtes hors ligne.",

      storiesTitle: "Mes histoires",
      storiesEmpty: "Pas encore d’histoires. Commencez dès maintenant !",
      storiesListEmpty: "Liste vide.",
      storiesRewrite: "Réécrire avec IA",
      storiesExport: "Exporter",
      storiesDelete: "Supprimer"
    },

    es: {
      footerAbout: "Memoir ayuda a las familias a capturar historias de vida con voz, transcripción por IA y reescrituras pulidas.",
      footerLegal: "Aviso legal y políticas",

      brandKicker: "APLICACIÓN MEMOIR",
      heroTitleA: "Conserva tus",
      heroTitleB: "Recuerdos para siempre",
      heroBlurb: "Graba una vez y guárdalo para generaciones. Empieza con un toque, añade un título y “cuándo ocurrió”, y compártelo de forma segura con tu familia.",

      miniStartLabel: "Empezar a grabar",
      miniStartCopy: "Un toque para comenzar. Añade un título y “cuándo ocurrió” después.",
      startRecording: "Grabar",
      miniStoriesLabel: "Ver mis historias",
      miniStoriesCopy: "Explora, reescribe con IA, exporta y comparte con tu familia.",
      viewStories: "Mis historias",

      whyTitle: "Por qué Memoir",
      feat1Title: "Transcripción precisa",
      feat1Copy: "Captura cada palabra con Whisper para gran exactitud.",
      feat2Title: "Reescritura IA para la familia",
      feat2Copy: "Convierte tus palabras habladas en historias literarias y cautivadoras para leer en familia.",
      feat3Title: "Privado o compartido",
      feat3Copy: "Guarda tus historias privadas o compártelas con miembros seleccionados; sincronizadas en todos tus dispositivos.",

      pricingTitle: "Precios",
      tierFreeName: "Gratis", tierFreePrice: "0 €",
      tierFreeB1: "Hasta 10 historias",
      tierFreeB2: "Máx. 2 min de transcripción cada una",
      tierFreeB3: "Biblioteca privada en todos tus dispositivos",

      tierPremiumName: "Narrador — 6,99 €/mes", tierPremiumPrice: "6,99 € / mes",
      tierPremiumB1: "Hasta 2,5 h / mes de transcripción IA",
      tierPremiumB2: "Reescritura IA, exportación PDF/CSV",
      tierPremiumB3: "Procesamiento prioritario",

      tierFamilyName: "Familiar — 8,99 €/mes", tierFamilyPrice: "8,99 € / mes",
      tierFamilyB1: "Todo en Narrador",
      tierFamilyB2: "Comparte tu biblioteca con hasta 4 miembros",
      tierFamilyB3: "Invita por correo; revoca en cualquier momento",

      tierExclusiveName: "Exclusivo — 11,99 €/mes", tierExclusivePrice: "11,99 € / mes",
      tierExclusiveB1: "Hasta 5 h / mes transcripción + reescritura IA",
      tierExclusiveB2: "Compartir con la familia (hasta 4)",
      tierExclusiveB3: "Mejor para narradores activos",

      recordTitle: "Grabar",
      recordButton: "Grabar",
      stop: "Detener",
      recordingHint: "Grabando… la transcripción aparecerá en vivo.",
      listening: "Escuchando…",
      offlineHint: "Sin conexión — audio guardado, se sincronizará después.",
      recordFree: "Gratis",
      recordGuided: "Guiado",
      guidedLead: "Elige un tema para inspirar tu memoria:",
      notesLabel: "Notas (opcional)",
      notesPlaceholder: "Añadir una nota rápida…",
      titleLabel: "Título",
      titlePlaceholder: "Título de la historia",
      whenLabel: "¿Cuándo ocurrió?",
      whenPlaceholder: "ej. “verano 1945”, “principios 2018”, “15 feb 1972”",
      photoLabel: "Añadir foto (opcional)",
      transcriptLabel: "Transcripción",
      transcriptEmpty: "Tus palabras aparecerán aquí…",
      saveStory: "Guardar historia",
      rewriteHint: "Consejo: usa Reescritura IA en “Mis historias” para convertir tus relatos en historias literarias.",
      storyDefault: "Historia",
      noTranscript: "No hay transcripción aún. Habla un poco y prueba otra vez.",
      saved: "¡Guardado! Encuéntralo en Mis historias.",
      saveFailed: "Error al guardar. Reintento automático sin conexión.",

      storiesTitle: "Mis historias",
      storiesEmpty: "Aún no tienes historias. Graba tu primera.",
      storiesListEmpty: "Lista vacía.",
      storiesRewrite: "Reescribir con IA",
      storiesExport: "Exportar",
      storiesDelete: "Eliminar"
    },

    nl: {
      footerAbout: "Memoir helpt families levensverhalen vast te leggen met mooie stemopnames, AI-transcriptie en verzorgde herschrijvingen.",
      footerLegal: "Juridische info & beleid",

      brandKicker: "MEMOIR APP",
      heroTitleA: "Bewaar je",
      heroTitleB: "Herinneringen voor altijd",
      heroBlurb: "Neem één keer op, bewaar voor generaties. Start met één tik, voeg een titel en “wanneer het gebeurde” toe en deel veilig met je familie.",

      miniStartLabel: "Opname starten",
      miniStartCopy: "Eén tik om te beginnen. Voeg later een titel en “wanneer het gebeurde” toe.",
      startRecording: "Starten",
      miniStoriesLabel: "Bekijk mijn verhalen",
      miniStoriesCopy: "Blader, herschrijf met AI, exporteer en deel met je familie.",
      viewStories: "Mijn verhalen",

      whyTitle: "Waarom Memoir",
      feat1Title: "Nauwkeurige transcriptie",
      feat1Copy: "Leg elk woord vast met Whisper voor hoge nauwkeurigheid.",
      feat2Title: "AI-herschrijving voor families",
      feat2Copy: "Maak van je gesproken woorden verzorgde verhalen — echte literatuur om samen te lezen.",
      feat3Title: "Privé of gedeeld",
      feat3Copy: "Houd verhalen privé of deel lees-alleen met familieleden; alles wordt gesynchroniseerd op je apparaten.",

      pricingTitle: "Prijzen",
      tierFreeName: "Gratis", tierFreePrice: "€0",
      tierFreeB1: "Tot 10 verhalen",
      tierFreeB2: "Max 2 minuten transcriptie per verhaal",
      tierFreeB3: "Privébibliotheek op al je apparaten",

      tierPremiumName: "Verteller — €6,99/maand", tierPremiumPrice: "€6,99 / maand",
      tierPremiumB1: "Tot 2,5 uur / maand AI-transcriptie",
      tierPremiumB2: "AI-herschrijving, export naar PDF/CSV",
      tierPremiumB3: "Prioriteitsverwerking",

      tierFamilyName: "Familie — €8,99/maand", tierFamilyPrice: "€8,99 / maand",
      tierFamilyB1: "Alles in Verteller",
      tierFamilyB2: "Deel met max. 4 familieleden (lees-alleen)",
      tierFamilyB3: "Uitnodigen via e-mail; altijd intrekbaar",

      tierExclusiveName: "Exclusief — €11,99/maand", tierExclusivePrice: "€11,99 / maand",
      tierExclusiveB1: "Tot 5 uur / maand AI-transcriptie + herschrijving",
      tierExclusiveB2: "Gezinsdeling (tot 4)",
      tierExclusiveB3: "Beste keuze voor actieve vertellers",

      recordTitle: "Opnemen",
      recordButton: "Opnemen",
      stop: "Stoppen",
      recordingHint: "Bezig met opnemen… transcript verschijnt live.",
      listening: "Luisteren…",
      offlineHint: "Offline — audio opgeslagen en later gesynchroniseerd.",
      recordFree: "Gratis",
      recordGuided: "Geleid",
      guidedLead: "Kies een onderwerp om je geheugen te prikkelen:",
      notesLabel: "Notities (optioneel)",
      notesPlaceholder: "Voeg een korte notitie toe…",
      titleLabel: "Titel",
      titlePlaceholder: "Verhaaltitel",
      whenLabel: "Wanneer gebeurde dit?",
      whenPlaceholder: "bijv. “zomer 1945”, “begin 2018”, “15 feb 1972”",
      photoLabel: "Foto toevoegen (optioneel)",
      transcriptLabel: "Transcript",
      transcriptEmpty: "Je woorden verschijnen hier…",
      saveStory: "Verhaal opslaan",
      rewriteHint: "Tip: gebruik AI-herschrijving in “Mijn verhalen” om je verhaal boekwaardig te maken.",
      storyDefault: "Verhaal",
      noTranscript: "Nog geen transcriptie. Spreek wat woorden en probeer opnieuw.",
      saved: "Opgeslagen! Je vindt het terug
